services:
  redis:
    image: "redis:8.2-rc1-bookworm"
  kafka:
    image: apache/kafka:4.1.0-rc0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  web:
    build: .
    depends_on:
      - redis
      - kafka
    restart: on-failure
    environment:
      WEB_NO_ENV: 1
      WEB_KAFKA_BROKER: kafka:9092
      WEB_REDIS_HOST: redis
      WEB_REDIS_PORT: 6379
    ports:
      - 8000:8000
